Feature/button see more products
MinisterioPublicoRJ/mprj-dcl pull request #132
Opened 2022-02-01 18:30 UTC by re-andrade1987

2022-02-01 19:45 UTC, LaylaCsAvila requested changes

2022-02-01 19:45 UTC, LaylaCsAvila commented on src/api/endpoints.js
> +export const PRODUCT_COMPONENT_DATA = (nextPos, extraFilters) => `${BASE_URL}?q=type:produtos&start=${nextPos}&fq=${extraFilters}&fl=title,name,res_name,res_url,res_format,extras_product_thumbnail_de
Era pra isso aqui mudar mesmo ou foi acidente?

2022-02-01 19:45 UTC, LaylaCsAvila commented on src/components/navbar/Navbar.module.css
> +  height: calc(var(--navbarHeight) * 1.2)
Isso vai quebrar muita coisa no layout, porque outros componentes estão lendo `navbarHeight` pra calcular suas alturas. Pode alterar o valor direto na variável.

2022-02-01 19:51 UTC, LaylaCsAvila requested changes

2022-02-01 19:51 UTC, LaylaCsAvila commented on src/components/navbar/Navbar.jsx
> +            </div>*/}
Não deletar

2022-02-01 19:51 UTC, LaylaCsAvila commented on src/components/navbar/dropdownProducts/DropdownProducts.jsx
> -
Não deletar

2022-02-01 20:07 UTC, re-andrade1987 commented on src/api/endpoints.js
> +export const PRODUCT_COMPONENT_DATA = (nextPos, extraFilters) => `${BASE_URL}?q=type:produtos&start=${nextPos}&fq=${extraFilters}&fl=title,name,res_name,res_url,res_format,extras_product_thumbnail_de
sim

2022-02-02 15:21 UTC, LaylaCsAvila approved these changes

2022-02-02 15:21 UTC, merged